name: HEXO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      ...
      - name: Submit the sitemap to baidu 
        run: |
          sh endPoint.sh public/
          curl -H 'Content-Type:text/plain' --data-binary @updatesitemap.txt "http://data.zz.baidu.com/urls?site=https://blog.evil-scream.cn&token=RQb88qnWj5MUFOYp"
      ...
